### ISSUE TITLE
Types of tokenizers 

### ISSUE THREAD

**Issue by EmilHvitfeldt** [EmilHvitfeldt/textrecipes#1]
Hello @topepo and welcome to the package!

I have just finished hacking out the first working prototype of the `step_tokenize` function.

``` r
library(recipes)
library(dplyr)
library(textrecipes)
set.seed(313)
examples <- matrix(exp(rnorm(40)), ncol = 2)
examples <- as.data.frame(examples) %>%
  mutate(text = janeaustenr::emma[1:20])

rec <- recipe(~ ., data = examples)

token_trans <- rec %>%
  step_tokenize(matches("text"))

token_obj <- prep(token_trans, training = examples, stringsAsFactors = FALSE)
transformed_tk <- bake(token_obj, examples)
transformed_tk
#> # A tibble: 20 x 3
#>       V1    V2 text      
#>    <dbl> <dbl> <list>    
#>  1 0.998 1.13  <chr [1]> 
#>  2 2.03  1.30  <chr [0]> 
#>  3 2.20  0.754 <chr [3]> 
#>  4 0.337 0.819 <chr [0]> 
#>  5 2.33  2.16  <chr [0]> 
#>  6 1.33  0.168 <chr [0]> 
#>  7 0.874 1.93  <chr [0]> 
#>  8 0.671 0.508 <chr [2]> 
#>  9 0.635 0.143 <chr [0]> 
#> 10 2.83  0.690 <chr [0]> 
#> 11 0.503 0.104 <chr [0]> 
#> 12 1.26  0.195 <chr [2]> 
#> 13 0.367 0.639 <chr [0]> 
#> 14 0.515 0.920 <chr [0]> 
#> 15 1.53  1.06  <chr [10]>
#> 16 0.202 0.346 <chr [12]>
#> 17 0.539 0.176 <chr [13]>
#> 18 5.18  2.14  <chr [6]> 
#> 19 1.50  1.74  <chr [0]> 
#> 20 1.37  1.07  <chr [12]>
```

Created on 2018-09-11 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).

 Before I go further with this step I would like to hear your opinion on a design matter.

Lets say I wanted to do tokenization with a [tokenizers](https://github.com/ropensci/tokenizers), [udpipe](https://github.com/bnosac/udpipe) and [TensorFlow](https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/text/Tokenizer) backend. How should that be done? Are me going to use separete step functions (`step_tf_tokenize` & `step_tokenize`) Or should it be done using a engine argument in the `step_tokenize` function or should I/we make an executive decision with regard to the tokenizer engine? 

If it is the latter. How would documentation be done since the passed arguments would differ from engine to engine?

**Comment by topepo** [comment]
I think that my preference is to have one `step_tokenize` with a method argument (and an `opts` argument for a list of extra arguments to get underlying function)...

_unless_ that's overly complex. 

For example, I did a single function for likelihood encoding in the `embed` package but ended up splitting it out because a single function had too many if/thens to be supportable. If you can write concise functions, similar to how you have `token_fun` right now, then a simple switch would be good.
