### ISSUE TITLE
tokenization step notes

### ISSUE THREAD

**Issue by topepo** [EmilHvitfeldt/textrecipes#5]
Looks good! Some small comments:

 * use `recipes::check_type` around [here](https://github.com/EmilHvitfeldt/textrecipes/blob/a9db4cbfd8da91658220d03678f3b2e6c4eaa8d1/R/tokenize.R#L68) to make sure that qualitative data are being specified. 
 * `step_tokenize` should probably have an `opts` argument to pass arguments directly to `tokenizers::tokenize_words`.
 * `token_fun` should check for character data and convert if the data are encoded otherwise.

**Comment by topepo** [comment]
Also, `prep` should have an `training` argument

**Comment by EmilHvitfeldt** [comment]
Thank you very much! I have incorporated all the suggestions.
