### ISSUE TITLE
Stopwords step

### ISSUE THREAD

**Issue by kanishkamisra** [EmilHvitfeldt/textrecipes#7]
Hey Emil and Max,

This package has been something I have been wondering about for months now, thanks a lot for going ahead and creating it! 

I was wondering if I could work on `step_stopwords` (and more steps in the future) and be a part of the package, I have already coded up some ideas for this and will be ready with a PR soon + will be doing so for more steps that I think could be important as part of an NLP pipeline (will add them to the readme table as I formalize descriptions + how the I/O should look like to match the tidy philosophy).

**Comment by EmilHvitfeldt** [comment]
I just merged you `step_stopwords`  PR. Nice job. Couple of minor details. You forgot to change the table in the readme and you didn't seem to add any tests for the step. I'll fix both of those issues right now. 

For further work, please verify with me new steps before you send a PR so that we don't double-work.

**Comment by kanishkamisra** [comment]
Got it! Sorry about that :( I need to still get used to test driven development.

What is the best way to contact you for further work?

**Comment by EmilHvitfeldt** [comment]
No problem! 

if you need any help you can refer to http://r-pkgs.had.co.nz/tests.html. Another useful source of information is to look at the testing done in more developed packages. 

Opening a issue is fine. I should be done with the steps in the readme table in the next couple of days, but if you have any suggestions for other steps don't hesitate to open an issue and we will see if it fits in.

**Comment by kanishkamisra** [comment]
I can start working on `step_text_filter` (this time with tests!) if that is okay with you? Also I had some questions about `step_word2vec` but I'll highlight these in a new issue to keep things organized.

**Comment by kanishkamisra** [comment]
No problem! Let me know :)
